---
version: 2.1
workflows:
  build:
    jobs:
      - setup
jobs:
  setup:
    docker:
      - image: golang:1.14.4
        environment:
          CGO_ENABLED: "0"
    steps:
      - checkout
      - run:
          name: Install golangci-lint
          command: |
            bash ci/install-golangci-lint.sh
