---
version: 2.1
workflows:
  build:
    jobs:
      - setup
jobs:
  setup:
    docker:
      - image: golang:1.14.15-alpine3.11
        environment:
          CGO_ENABLED: "0"
    steps:
      - run:
          name: Install golangci-lint
          command: |
            apk add curl
            GOLANGCI_VERSION=v1.27.0
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin "$GOLANGCI_VERSION"
