---
name: CI
on: [push, pull_request]
env:
  tf_version: '0.12.20'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14.0'
      - name: golangci-lint
        run: |
          GOLANGCI_VERSION=v1.28.0
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin "$GOLANGCI_VERSION"
